"""Scaffold a self-contained, Prefect Horizon-deployable MCP project from a workspace's data."""

import shutil
from pathlib import Path

from . import __version__
from .workspace import MODE_MARKER_NAME

REPO_URL = "https://github.com/patrickhegnauer/martech_knowledge-graph.git"

SERVER_PY = '''"""Horizon entrypoint: server.py:mcp"""

from pathlib import Path

from martech_knowledge_graph.mcp_server import create_mcp

mcp = create_mcp(Path(__file__).parent / "data")
'''

README_TEMPLATE = """# {name} (MCP server for Prefect Horizon)

Generated by `martech-knowledge-graph export-mcp`. This folder is a snapshot of your knowledge graph
({count} data file(s) in `data/`) plus the tiny entrypoint Horizon needs.

**Put this in a PRIVATE GitHub repository** - `data/` contains your curated business context.

## Deploy

1. Create a private GitHub repo and push this folder to `main`.
2. Sign in at https://horizon.prefect.io with GitHub, create a new server, pick the repo.
3. Entrypoint: `server.py:mcp`. Horizon builds from `requirements.txt` and gives you a URL like
   `https://<your-name>.fastmcp.app/mcp`.
4. Add that URL as a custom connector in claude.ai (Horizon handles OAuth).

## Update

Data is a snapshot. After changing context in the web UI, re-run
`martech-knowledge-graph export-mcp --out <this folder>`, commit, push - Horizon redeploys automatically.
"""


def export_mcp_project(out_dir: Path, source_dir: Path, name: str) -> int:
    ttl_files = sorted(Path(source_dir).glob("*-instances.ttl"))
    if not ttl_files:
        raise SystemExit(f"No *-instances.ttl files in {source_dir} - nothing to export.")

    out_dir = Path(out_dir)
    data_dir = out_dir / "data"
    if data_dir.exists():
        shutil.rmtree(data_dir)
    data_dir.mkdir(parents=True)

    for f in ttl_files:
        shutil.copy2(f, data_dir / f.name)
    (data_dir / MODE_MARKER_NAME).write_text("org", encoding="utf-8")

    pin = f"@v{__version__}"
    (out_dir / "server.py").write_text(SERVER_PY, encoding="utf-8")
    (out_dir / "requirements.txt").write_text(
        f"martech-knowledge-graph @ git+{REPO_URL}{pin}\n", encoding="utf-8"
    )
    (out_dir / "README.md").write_text(
        README_TEMPLATE.format(name=name, count=len(ttl_files)), encoding="utf-8"
    )
    return len(ttl_files)

