"""
Journey builder — describe a journey as structured Python, get correct
turtle out. Doesn't decide content for you (requirement wording, KPI
formulas, component definitions still need a human/judgment call) --
it just guarantees the RDF syntax is right and handles the fiddly
n-ary Measurement logic automatically.

Usage: see build_example_ecommerce() / build_example_login() at the
bottom for two worked examples that reproduce the existing files.
"""

import re
from dataclasses import dataclass, field


ONTOLOGY_NS = "https://example.org/martech/ontology/"

# Prefix for generated Component refs (Component.xdm_path gets appended to this).
# Org-specific -- overridable per call; server.py's /api/journeys/generate reads
# the persisted per-workspace setting (.mkg-settings.json) and passes it through.
DEFAULT_XDM_BASE_URL = "https://sandbox/SANDBOX_NAME/xdm/"


@dataclass
class ComponentSpec:
    key: str                 # short internal key, e.g. "product_views" -- used to link stages to this component
    label: str
    component_type: str      # "metric" | "dimension"
    definition: str
    caveats: str
    context: str
    owner: str
    xdm_path: str            # e.g. "commerce.productViews.value" -- becomes the refs URI
    refs: list = None        # full ref URIs; when set they are emitted verbatim instead of xdm_base_url + xdm_path


@dataclass
class StageSpec:
    key: str
    label: str
    order: int
    component_key: str       # which ComponentSpec.key measures this stage
    filter_value: str = None # only needed when multiple stages share one component
    rolls_up_to_kpi: bool = False


@dataclass
class JourneySpec:
    slug: str                # used for the data namespace and the output filename
    journey_label: str
    requirement_label: str
    requirement_comment: str
    kpi_label: str
    kpi_formula: str
    kpi_owner: str
    kpi_target: float = None
    kpi_comment: str = None
    journey_owner: str = None
    components: list = field(default_factory=list)   # list[ComponentSpec]
    stages: list = field(default_factory=list)        # list[StageSpec]
    data_layer_variable: str = None
    data_layer_source_system: str = "Web data layer (digitalData)"


def _esc(s):
    """Make a value safe inside a turtle string literal (double quotes become single quotes)."""
    return (s.replace("\\", "\\\\").replace('"', "'")
            .replace("\r\n", "\n").replace("\n", "\\n").replace("\r", "\\n").replace("\t", " "))


def slugify(text, fallback="item"):
    return re.sub(r"[^a-z0-9]+", "_", (text or "").lower()).strip("_") or fallback


def build_journey_turtle(spec: JourneySpec, xdm_base_url: str = DEFAULT_XDM_BASE_URL,
                         existing_components: dict = None) -> str:
    """existing_components maps component key -> URI of a component already defined elsewhere in the
    workspace; those are referenced instead of redefined, so their curated context is kept."""
    existing_components = existing_components or {}

    def comp_ref(key):
        return f"<{existing_components[key]}>" if key in existing_components else f"data:component_{key}"

    data_ns = f"https://example.org/martech/data/{spec.slug}/"
    lines = [
        f"# ==========================================================================",
        f"# {spec.journey_label} — instance data",
        f"# Generated by journey_builder.py -- conforms to martech-ontology.ttl",
        f"# ==========================================================================",
        "",
        f'@prefix martech: <{ONTOLOGY_NS}> .',
        f'@prefix data:    <{data_ns}> .',
        '@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .',
        "",
        "# --------------------------------------------------------------------------",
        "# Requirement",
        "# --------------------------------------------------------------------------",
        "",
        "data:req a martech:Requirement ;",
        f'    rdfs:label "{_esc(spec.requirement_label)}" ;',
        f'    rdfs:comment "{_esc(spec.requirement_comment)}" ;',
        '    martech:status "active" ;',
        "    martech:addressed_by data:kpi .",
        "",
        "# --------------------------------------------------------------------------",
        "# KPI",
        "# --------------------------------------------------------------------------",
        "",
        "data:kpi a martech:KPI ;",
        f'    rdfs:label "{_esc(spec.kpi_label)}" ;',
        f'    martech:formula "{_esc(spec.kpi_formula)}" ;',
        f'    martech:owner "{_esc(spec.kpi_owner)}" ;',
    ]
    kpi_tail = "."
    if spec.kpi_target is not None:
        lines.append(f"    martech:target {spec.kpi_target} ;")
    if spec.kpi_comment:
        lines.append(f'    rdfs:comment "{_esc(spec.kpi_comment)}" {kpi_tail}')
    else:
        # close the last line with a period instead of semicolon
        lines[-1] = lines[-1].rstrip(" ;") + " ."
    lines.append("")

    journey_lines = [
        "data:journey a martech:Journey ;",
        f'    rdfs:label "{_esc(spec.journey_label)}" ;',
    ]
    if spec.journey_owner:
        journey_lines.append(f'    martech:owner "{_esc(spec.journey_owner)}" ;')
    journey_lines.append(
        "    martech:has_stage " + ", ".join(f"data:stage_{s.key}" for s in spec.stages) + " ."
    )

    lines += [
        "# --------------------------------------------------------------------------",
        "# Journey",
        "# --------------------------------------------------------------------------",
        "",
        *journey_lines,
        "",
        "# --------------------------------------------------------------------------",
        "# Stages",
        "# --------------------------------------------------------------------------",
        "",
    ]

    for s in spec.stages:
        block = [f"data:stage_{s.key} a martech:Stage ;", f'    rdfs:label "{_esc(s.label)}" ;']
        if s.rolls_up_to_kpi:
            block.append(f"    martech:order {s.order} ;")
            block.append("    martech:rolls_up_to data:kpi .")
        else:
            block.append(f"    martech:order {s.order} .")
        lines += block + [""]

    lines += [
        "# --------------------------------------------------------------------------",
        "# Components",
        "# --------------------------------------------------------------------------",
        "",
    ]
    for c in spec.components:
        if c.key in existing_components:
            continue
        lines += [
            f"data:component_{c.key} a martech:Component ;",
            f'    rdfs:label "{_esc(c.label)}" ;',
            f'    martech:component_type "{c.component_type}" ;',
            f'    martech:definition "{_esc(c.definition)}" ;',
            f'    martech:caveats "{_esc(c.caveats)}" ;',
            f'    martech:context "{_esc(c.context)}" ;',
            f'    martech:owner "{_esc(c.owner)}" ;',
            "    martech:refs " + (", ".join(f"<{r}>" for r in c.refs) if c.refs else f"<{xdm_base_url}{c.xdm_path}>") + " .",
            "",
        ]

    if spec.data_layer_variable:
        used_component_keys = sorted({s.component_key for s in spec.stages})
        lines += [
            "# --------------------------------------------------------------------------",
            "# Data layer variable",
            "# --------------------------------------------------------------------------",
            "",
            "data:dlv a martech:DataLayerVariable ;",
            f'    rdfs:label "{_esc(spec.data_layer_variable)}" ;',
            f'    martech:source_system "{_esc(spec.data_layer_source_system)}" ;',
            "    martech:maps_to " + ", ".join(comp_ref(k) for k in used_component_keys) + " .",
            "",
        ]

    lines += [
        "# --------------------------------------------------------------------------",
        "# Measurements",
        "# --------------------------------------------------------------------------",
        "",
    ]
    for s in spec.stages:
        block = [
            f"data:measurement_{s.key} a martech:Measurement ;",
            f"    martech:measured_entity data:stage_{s.key} ;",
        ]
        if s.filter_value:
            block.append(f"    martech:measured_component {comp_ref(s.component_key)} ;")
            block.append(f'    martech:filter_value "{_esc(s.filter_value)}" .')
        else:
            block.append(f"    martech:measured_component {comp_ref(s.component_key)} .")
        lines += block + [""]

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Reverse direction -- read a journey file back into a JourneySpec so a form
# can edit it. Refuses anything it could not write back unchanged.
# ---------------------------------------------------------------------------

_ROUND_TRIP_PREDICATES = {
    "type", "label", "comment", "status", "addressed_by", "formula", "owner", "target", "has_stage", "order",
    "rolls_up_to", "component_type", "definition", "caveats", "context", "refs", "maps_to", "source_system",
    "measured_entity", "measured_component", "filter_value",
}
_ROUND_TRIP_TYPES = {"Requirement", "KPI", "Journey", "Stage", "Component", "DataLayerVariable", "Measurement"}


def _local(uri):
    return str(uri).rstrip("/").split("/")[-1].split("#")[-1]


def journey_from_graph(g, slug):
    """Returns (JourneySpec, None) or (None, reason). g must hold just this journey's file."""
    from rdflib import RDF, RDFS, Namespace
    M = Namespace(ONTOLOGY_NS)

    def one(node, pred):
        return g.value(node, pred)

    def text(node, pred, default=""):
        v = one(node, pred)
        return str(v) if v is not None else default

    for s, p, o in g:
        if p == RDF.type:
            name = _local(o)
            if name not in _ROUND_TRIP_TYPES:
                return None, f"contains a {name}, which the form cannot preserve"
        elif p == RDFS.label:
            continue
        elif p == RDFS.comment:
            continue
        elif _local(p) not in _ROUND_TRIP_PREDICATES or not str(p).startswith(ONTOLOGY_NS):
            return None, f"uses a property the form cannot preserve ({_local(p)})"

    journeys = list(g.subjects(RDF.type, M.Journey))
    kpis = list(g.subjects(RDF.type, M.KPI))
    reqs = list(g.subjects(RDF.type, M.Requirement))
    if len(journeys) != 1 or len(kpis) != 1 or len(reqs) != 1:
        return None, "must contain exactly one journey, one requirement and one KPI"
    journey, kpi, req = journeys[0], kpis[0], reqs[0]

    own_components = {}
    for c in g.subjects(RDF.type, M.Component):
        key = _local(c)[len("component_"):] if _local(c).startswith("component_") else _local(c)
        own_components[c] = ComponentSpec(
            key=key, label=text(c, RDFS.label), component_type=text(c, M.component_type),
            definition=text(c, M.definition), caveats=text(c, M.caveats), context=text(c, M.context),
            owner=text(c, M.owner), xdm_path="", refs=sorted(str(r) for r in g.objects(c, M.refs)),
        )

    measurements = {}
    for m in g.subjects(RDF.type, M.Measurement):
        stage = one(m, M.measured_entity)
        if stage in measurements:
            return None, "a stage is measured by more than one component"
        measurements[stage] = m

    stages = []
    for st in g.objects(journey, M.has_stage):
        m = measurements.get(st)
        comp = one(m, M.measured_component) if m is not None else None
        if comp is None:
            return None, f"stage '{text(st, RDFS.label)}' has no measured component"
        comp_key = own_components[comp].key if comp in own_components else (
            _local(comp)[len("component_"):] if _local(comp).startswith("component_") else _local(comp))
        name = _local(st)
        stages.append(StageSpec(
            key=name[len("stage_"):] if name.startswith("stage_") else name,
            label=text(st, RDFS.label), order=int(one(st, M.order) or 0), component_key=comp_key,
            filter_value=text(m, M.filter_value) or None, rolls_up_to_kpi=one(st, M.rolls_up_to) is not None,
        ))
    stages.sort(key=lambda s: s.order)

    dlvs = list(g.subjects(RDF.type, M.DataLayerVariable))
    if len(dlvs) > 1:
        return None, "contains more than one data layer variable"
    target = one(kpi, M.target)

    spec = JourneySpec(
        slug=slug, journey_label=text(journey, RDFS.label), journey_owner=text(journey, M.owner) or None,
        requirement_label=text(req, RDFS.label), requirement_comment=text(req, RDFS.comment),
        kpi_label=text(kpi, RDFS.label), kpi_formula=text(kpi, M.formula), kpi_owner=text(kpi, M.owner),
        kpi_target=float(target) if target is not None else None, kpi_comment=text(kpi, RDFS.comment) or None,
        components=list(own_components.values()), stages=stages,
        data_layer_variable=text(dlvs[0], RDFS.label) if dlvs else None,
        data_layer_source_system=(text(dlvs[0], M.source_system) if dlvs else "") or "Web data layer (digitalData)",
    )
    return spec, None


# ---------------------------------------------------------------------------
# CSV entry point -- fill in a spreadsheet instead of writing Python.
# One row per stage; journey/requirement/KPI/data-layer columns repeat
# the same value on every row.
# ---------------------------------------------------------------------------

import csv


def build_journey_from_csv(csv_path: str, xdm_base_url: str = DEFAULT_XDM_BASE_URL,
                           existing_components: dict = None) -> str:
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError("CSV has no data rows")

    first = rows[0]

    def yn(val):
        return str(val).strip().lower() in ("yes", "true", "1")

    def opt_float(val):
        return float(val) if val and val.strip() else None

    seen_components = {}
    components = []
    stages = []
    for row in rows:
        ckey = row["component_key"].strip()
        if ckey not in seen_components:
            spec = ComponentSpec(
                key=ckey,
                label=row["component_label"].strip(),
                component_type=row["component_type"].strip(),
                definition=row["component_definition"].strip(),
                caveats=row["component_caveats"].strip(),
                context=row["component_context"].strip(),
                owner=row["component_owner"].strip(),
                xdm_path=row["component_xdm_path"].strip(),
            )
            seen_components[ckey] = spec
            components.append(spec)

        stages.append(StageSpec(
            key=row["stage_key"].strip(),
            label=row["stage_label"].strip(),
            order=int(row["stage_order"]),
            component_key=ckey,
            filter_value=row.get("filter_value", "").strip() or None,
            rolls_up_to_kpi=yn(row.get("rolls_up_to_kpi", "")),
        ))

    spec = JourneySpec(
        slug=first["journey_slug"].strip(),
        journey_label=first["journey_label"].strip(),
        journey_owner=first.get("journey_owner", "").strip() or None,
        requirement_label=first["requirement_label"].strip(),
        requirement_comment=first["requirement_comment"].strip(),
        kpi_label=first["kpi_label"].strip(),
        kpi_formula=first["kpi_formula"].strip(),
        kpi_owner=first["kpi_owner"].strip(),
        kpi_target=opt_float(first.get("kpi_target", "")),
        kpi_comment=first.get("kpi_comment", "").strip() or None,
        components=components,
        stages=stages,
        data_layer_variable=first.get("data_layer_variable", "").strip() or None,
        data_layer_source_system=first.get("data_layer_source_system", "").strip() or "Web data layer (digitalData)",
    )
    return build_journey_turtle(spec, xdm_base_url=xdm_base_url, existing_components=existing_components)


CSV_COLUMNS = [
    "journey_slug", "journey_label", "journey_owner",
    "requirement_label", "requirement_comment",
    "kpi_label", "kpi_formula", "kpi_owner", "kpi_target", "kpi_comment",
    "stage_key", "stage_label", "stage_order", "rolls_up_to_kpi",
    "component_key", "component_label", "component_type",
    "component_definition", "component_caveats", "component_context",
    "component_owner", "component_xdm_path", "filter_value",
    "data_layer_variable", "data_layer_source_system",
]


def write_csv_template(path: str):
    """Write an empty template CSV with the right headers, ready to fill in."""
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        writer.writeheader()


# ---------------------------------------------------------------------------
# Worked examples -- reproducing the two existing journeys, to prove the
# builder generates equivalent (not necessarily byte-identical) turtle.
# ---------------------------------------------------------------------------

def build_example_ecommerce() -> JourneySpec:
    components = [
        ComponentSpec("product_views", "Product views", "metric",
            "Number of times a product detail page was viewed.",
            "Counts page views, not unique visitors — a visitor viewing the same product twice counts twice.",
            "Entry point for the purchase funnel; used to benchmark top-of-funnel demand.",
            "Digital Analytics", "commerce.productViews.value"),
        ComponentSpec("product_list_adds", "Product list adds", "metric",
            "Number of times a product was added to the cart.",
            "Does not deduplicate repeated adds of the same product within one session.",
            "First explicit purchase-intent signal in the funnel.",
            "Digital Analytics", "commerce.productListAdds.value"),
        ComponentSpec("checkouts", "Checkouts", "metric",
            "Number of times a user started the checkout process.",
            "Counts checkout starts, not completions — a user can start checkout multiple times without purchasing.",
            "Marks the transition from browsing to transactional intent.",
            "Digital Analytics", "commerce.checkouts.value"),
        ComponentSpec("orders", "Orders", "metric",
            "Number of completed purchase orders.",
            "Includes orders later cancelled or refunded — not net of returns.",
            "The funnel's terminal event and the numerator of the order conversion rate KPI.",
            "Digital Analytics", "orders"),
    ]
    stages = [
        StageSpec("product_view", "Product view", 1, "product_views"),
        StageSpec("cart_add", "Cart add", 2, "product_list_adds"),
        StageSpec("checkout", "Checkout", 3, "checkouts"),
        StageSpec("order", "Order", 4, "orders", rolls_up_to_kpi=True),
    ]
    return JourneySpec(
        slug="ecommerce",
        journey_label="Ecommerce purchase journey",
        requirement_label="Understand shop performance and drop-off",
        requirement_comment="We want to understand how our shop is performing, and where in the journey people drop off.",
        kpi_label="Order conversion rate",
        kpi_formula="Orders / Product Views",
        kpi_owner="Ecommerce / Digital Marketing",
        kpi_target=0.0020,
        kpi_comment="Current value (2026): 0.11%. Target: 0.20% (illustrative example, not a real commitment).",
        journey_owner="Digital Marketing",
        components=components,
        stages=stages,
        data_layer_variable="digitalData.conversion.conversionFunnel.step",
    )


def build_example_login() -> JourneySpec:
    components = [
        ComponentSpec("page_name", "Page name", "dimension",
            "The page name/path captured on each page view; used here to identify funnel steps by value.",
            "A shared, general-purpose dimension — filtering by value (e.g. /customer/login) is required to isolate a specific journey step. The raw component alone doesn't identify a stage.",
            "A general-purpose dimension, likely reused by other journeys in a real implementation — filtering by value is what distinguishes each specific use, not the component itself.",
            "Digital Analytics", "web.webPageDetails.name"),
    ]
    stages = [
        StageSpec("login", "Login", 1, "page_name", filter_value="/customer/login"),
        StageSpec("login_success", "Login success", 2, "page_name", filter_value="/customer/login/success", rolls_up_to_kpi=True),
    ]
    return JourneySpec(
        slug="login",
        journey_label="Customer login journey",
        requirement_label="Understand monthly login frequency",
        requirement_comment="We want to know how many logins we have monthly (MAU), and how that compares to overall sessions.",
        kpi_label="Monthly login rate",
        kpi_formula="Monthly logins / Sessions",
        kpi_owner="Product Analytics",
        kpi_target=0.35,
        kpi_comment="Target: 35% of monthly sessions include a login (illustrative example, not a real commitment).",
        journey_owner="Product Analytics",
        components=components,
        stages=stages,
        data_layer_variable="digitalData.page.pageInfo.name",
    )


if __name__ == "__main__":
    print(build_journey_turtle(build_example_ecommerce()))
